### ISSUE TITLE
Feature #1: User can log-in

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/Garden-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User will be able to log in with username and password. 

User can Log-in
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
After successful log in they will be directed to the "My Garden" page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="323" alt="Screenshot 2023-08-15 at 9 22 23 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/dca99b52-229a-4002-a5c8-a369460ee9d8">
<img width="323" alt="Screenshot 2023-08-15 at 9 23 07 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/16610e41-b84c-45cb-99d4-c83786d5c5a8">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update the "user" table to contain the new userId, username, password, createdAt, updatedAt rows.

### ☁️ Server Tasks

- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to hold form inputs.
- [x] Create a component that allows the user to register a new log in username/password.
- [x] Update component to hold the homepage/my garden 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by BenGrimmius** [comment]
![Kapture 2023-09-25 at 20 38 11](https://github.com/BenGrimmius/Garden-Project/assets/103142603/b7dae49e-ecfb-438a-96cf-fc8651f83c13)
