### ISSUE TITLE
Feature #2: User can browse a list of plants to add.

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/Garden-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse a list of different plants.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click on the plus icon on the top right corner of the screen and browse plants that they would like to add to their garden.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="240" alt="Screenshot 2023-08-17 at 6 42 51 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/ea798a08-b6c4-441b-ab61-75cd5f9cd6a2">
<img width="241" alt="Screenshot 2023-08-17 at 6 42 58 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/05456920-d695-4152-8018-22dc78cb17db">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to be used as a "back" button to return to "My Garden"
- [x] Create a form component that will take text.
- [x] Update components to display different plants according to what the user has inputed in the text box referenced in prior step.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
