### ISSUE TITLE
Feature #3: User can view descriptions/ facts of the list of plants

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/Garden-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view facts of selected plants.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view descriptions and facts regarding specific plants in the list of plants. The user can display the text by pressing the plus button, and hide them by pressing the minus button(or pressing the plus button on another plant in an accordion fashion)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="258" alt="Screenshot 2023-08-17 at 6 51 29 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/445f93d1-4306-442a-9f32-38380c251cd7">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Create a components button that will expand text content.
- [ ] Update the component if the user clicks on another button on another plant, the previous plant's text content will be hidden and the new plant's text content will be shown.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
