### ISSUE TITLE
Feature #4: User can add plants to their garden.

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/Garden-Project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add plants to their garden.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on the + icon and add plants to their garden. The plants will then be displayed in their garden in the homepage.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="259" alt="Screenshot 2023-08-17 at 6 57 56 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/f7c70078-aa85-491e-bdcb-5f86bb5450f0">
<img width="260" alt="Screenshot 2023-08-17 at 6 58 16 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/08bb4a1e-fcac-4ed4-b8f5-019db7007287">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component button that will add the plant to the user's garden db table and add the plant to the user's garden
- [ ] Update the component from a + to a - when the user clicks on it. 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
