### ISSUE TITLE
Feature #5: User can remove plants from their garden

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/Garden-Project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove plants from their garden.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to remove plants from their garden from the "My Garden" screen by clicking the "X" in the top right corner of the component.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="280" alt="Screenshot 2023-08-17 at 7 13 48 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/3c619e0a-cae7-4100-a1fb-0899a8e63de8">
<img width="280" alt="Screenshot 2023-08-17 at 7 14 03 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/10d795b1-746f-4256-b3b8-f201abcf2ba9">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update the garden table to remove the plants from the garden table.

### ⚡ Client Tasks

- [ ] Create a component display an "X" button on the top right of the plant's wrapper.
- [ ] Update component to remove the plant from the home screen.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
