### ISSUE TITLE
Feature #6: User can view the week's weather.

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/Garden-Project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the weather conditions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The week's weather will be displayed along the bottom of the screen with icons according to the weather status and the temperature in fahrenheit.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="276" alt="Screenshot 2023-08-17 at 7 19 00 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/f077f0be-1375-4cb6-b84b-a30428b8d8f8">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `weather` table  to add the week's weather. 

### ☁️ Server Tasks

- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to display an icon and temperature of a day of the week.
- [ ] Render this component 7 times to display previous and next days in relation to the current day.
- [ ] Update component to display weather in real time.
### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
