### ISSUE TITLE
Feature #7: User can sign out

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/Garden-Project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can press the "Sign Out" button on the top left corner of the screen to sign out. The "Sign in or register" screen will then be displayed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="277" alt="Screenshot 2023-08-17 at 7 22 36 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/5fa94668-6d36-4e26-9516-fdc1d09f0105">
<img width="276" alt="Screenshot 2023-08-17 at 7 22 48 PM" src="https://github.com/BenGrimmius/Garden-Project/assets/103142603/15fee081-ee90-4595-b0bd-fed1acb04ab0">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Create a component to act as a sign out button. No borders. In a color that will stand out but still be discrete.
- [ ] Update the screen to display the "Sign in" screen.
### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
